Natural Language Processing

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

In [4]:
#data preprocessing
dataset=pd.read_csv('/content/Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [5]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))


In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
!pip install tensorflow


In [13]:
#building ANN
ann= tf.keras.models.Sequential()


In [14]:
#adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [15]:
#adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [16]:
#adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [17]:
#compiling the ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [18]:
#training the ann on training set

ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.6342 - accuracy: 0.6680
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4897 - accuracy: 0.7921
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4529 - accuracy: 0.7999
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.8035
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4291 - accuracy: 0.8080
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8129
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4190 - accuracy: 0.8156
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4144 - accuracy: 0.8170
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 0.8201
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4018 - accura

In [22]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)


1/1 [==============================] - 0s 22ms/step
[[False]]


In [23]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 200  205]]


0.858